version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8004
        volumes:
            - ./app:/usr/src/app
        ports:
            - "8004:8004"
        depends_on:
            - db
    sshd:
        image: rastasheep/ubuntu-sshd
        ports:
            - "49901:22"
