# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.CharField(max_length=50)),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
