# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160327_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
