# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='link_url',
        ),
    ]
