# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('blog', '0003_blogarticle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='title',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
