# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160317_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='body_stream',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())), default=''),
            preserve_default=False,
        ),
    ]
