version: '2'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: wqAPMpnhwVuUMrG7unL9B
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
    nginx:
        build: nginx
        ports:
            - "80:80"
        volumes_from:
            - web
    web:
        build:
            context: ../
            dockerfile: deploy/Dockerfile
        depends_on:
            - db
        volumes:
            - /usr/src/static
            - /usr/src/media
        environment:
            DJANGO_SETTINGS_MODULE: 'snowdoniadragons.settings.production'
