# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160227_1009'),
        ('session', '0002_auto_20160227_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiongameplayed',
            name='game',
        ),
        migrations.RemoveField(
            model_name='sessiongameplayed',
            name='page',
        ),
        migrations.RemoveField(
            model_name='session',
            name='played_games',
        ),
        migrations.AddField(
            model_name='session',
            name='played_games',
            field=models.ManyToManyField(to='base.Game'),
        ),
        migrations.DeleteModel(
            name='SessionGamePlayed',
        ),
    ]
