# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160227_1009'),
        ('session', '0003_auto_20160227_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_played', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Game')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_played', to='session.Session')),
            ],
        ),
    ]
