# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_sessiongame'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, help_text='Leave blank if this is just a regular session', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
