# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_remove_session_played_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrelated',
            name='link_page',
        ),
    ]
