# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('session', '0007_remove_sessionrelated_link_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrelated',
            name='link_document',
        ),
        migrations.AddField(
            model_name='sessionrelated',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
