# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20160227_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrelated',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
