# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_sessionrelated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrelated',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
