# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_venue'),
        ('session', '0011_auto_20160327_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Venue'),
        ),
    ]
