# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_session_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Only needed if the venue is different from the regular venue', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Venue'),
        ),
    ]
