# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_auto_20160327_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='game_group',
        ),
    ]
