# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_remove_session_game_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='forum_thread',
            field=models.URLField(blank=True),
        ),
    ]
