# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.wagtailroutablepage.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('summary', models.CharField(max_length=500)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('colour', models.CharField(max_length=8)),
                ('forum_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Venue')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='GroupIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(blank=True, help_text='Leave blank if this is just a regular session', max_length=255)),
                ('date', models.DateTimeField(verbose_name='Session date')),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('forum_thread', models.URLField(blank=True)),
                ('venue', models.ForeignKey(blank=True, help_text='Only needed if the venue is different from the regular venue', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Venue')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_played', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Game')),
                ('session', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_played', to='group.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('session', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='group.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('session', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_media', to='group.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
