# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 15:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='related',
            field=wagtail.wagtailcore.fields.StreamField((('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())), default=''),
            preserve_default=False,
        ),
    ]
