# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 16:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_session_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='games',
            field=wagtail.wagtailcore.fields.StreamField((('game', wagtail.wagtailcore.blocks.StructBlock((('game', wagtail.wagtailcore.blocks.CharBlock()),))),), default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='related',
            field=wagtail.wagtailcore.fields.StreamField((('blog', wagtail.wagtailcore.blocks.PageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock()))),
        ),
    ]
