# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.AddField(
            model_name='group',
            name='summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
