# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20160225_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='location_coords',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
