# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20160705_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='games',
        ),
        migrations.AlterField(
            model_name='session',
            name='related',
            field=wagtail.wagtailcore.fields.StreamField((('blog', wagtail.wagtailcore.blocks.PageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiongame',
            name='times_played',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
