# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20160227_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='colour',
            field=models.CharField(default='eeeeeee', max_length=8),
            preserve_default=False,
        ),
    ]
