# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_venue'),
        ('group', '0005_group_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='location_coords',
        ),
        migrations.AddField(
            model_name='group',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Venue'),
            preserve_default=False,
        ),
    ]
